baseURL = 'https://gleiria.github.io/'
languageCode = 'en-gb'
theme = "anatole"
enableEmoji = true

[params]
title = "Gonçalo Leiria"
author = "Gonçalo Leiria"
description = """Exploring Computer Science and AI in Health Care
⚠️ website under construction ⚠️"""
profilePicture = "images/profile_picture.png"
mainSections = ["blog"]


## Menu items
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 1
  url = "/home/"

  [[menu.main]]
  name = "Blog"
  weight = 2
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "contact"
  weight = 3
  identifier = "contact"
  url = "/contact/"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/gleiria/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:g.n.leiria@exeter.ac.uk"









      
   







