baseURL = 'https://gleiria.github.io/'
languageCode = 'en-gb'
theme = "anatole"
enableEmoji = true


[params]
title = "Code Currents"
author = "Gonçalo Leiria"
description = "Exploring Computer Science and Clinical-AI"
profilePicture = "images/profile_picture.png"
mainSections = ["blog"]
