baseURL = 'https://gleiria.github.io/'
languageCode = 'en-gb'
theme = "anatole"
enableEmoji = true


[params]
title = "Code Currents"
author = "Gonçalo Leiria"
description = "Exploring Computer Science and Clinical-AI"
profilePicture = "images/profile_picture.png"
mainSections = ["blog"]


## Menu items
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 1
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 2
  identifier = "blog"
  url = "/blog/"

  [[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/gleiria/"